# Generated by Django 2.1 on 2018-10-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20181020_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
