# Generated by Django 2.1 on 2018-11-17 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20181117_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskwork',
            name='task_assignment',
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_tasks',
            field=models.ManyToManyField(blank=True, to='tracking.Task'),
        ),
        migrations.AddField(
            model_name='taskwork',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='tracking.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskwork',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='tracking.Task'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TaskAssignment',
        ),
    ]
